version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minimalist-chat-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      FAKE_AI: "0"  # 设置为 0 使用真实 Gemini API，设置为 1 使用复读模式
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: "gemini-2.5-flash"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: minimalist-chat-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
